name: merge_to_testflight

on:
  # Merge dev into master every day at midnight GMT
  schedule:
    - cron:  '0 0 * * *'

jobs:
  merge_to_master:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: testflight
    - name: Merge Dev into testflight
      run: |
        git checkout dev 
        git pull
        git checkout testflight
        git merge dev
        git push origin testflight