name: pull_request

on:
  pull_request:
    branches: [master, dev]
env:
  DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

jobs:

  xcodebuild:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Xcode Build
      run: |
        gem install bundler:1.16.6
        bundle install
        xcodebuild clean build -workspace COVIDWatch.xcworkspace -scheme 'COVIDWatch iOS' CODE_SIGNING_ALLOWED=NO | xcpretty

  swiftlint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: SwiftLint
      run: |
        ./Pods/SwiftLint/swiftlint --strict