name: swiftlint

on:
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  strict_linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Xcode Build
        run: |
          pwd
          ls
          ./Pods/SwiftLint/swiftlint --strict
